# Generated by Django 3.2.5 on 2021-08-02 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Nome')),
                ('date', models.DateField(verbose_name='Data')),
                ('start', models.TimeField(verbose_name='Inicio')),
                ('end', models.TimeField(max_length=5, verbose_name='Fim')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereco')),
                ('endereco2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereco 2')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresamodel')),
            ],
        ),
    ]
